### ISSUE TITLE
Something about "Conv5"

### ISSUE THREAD

**Issue by chenpengf0223** [Zhengtq/shufflenetv2-tensorflow2.0#1]
@Zhengtq  Hi, thanks for your great work!
It seems that the code does not contain "Conv5"，which is used to mix up features. I attach the picture, "Conv5" has 1024 output channels.
![image](https://user-images.githubusercontent.com/20535427/88357232-260a7300-cd9d-11ea-990f-4f117186fb48.png)

As the paper says:
The overall network structure is similar to ShufﬂeNet v1 [15] and summarized in Table 5. There is only one diﬀerence: an additional 1×1 convolution layer is added right before global averaged pooling to mix up features, which is absent in ShuﬄeNet v1.

**Comment by Zhengtq** [comment]
Very thanks for your carefully pointing out. It's indeed my mistake. I have modified it now. Hope for more communication with you.

**Comment by Zhengtq** [comment]
> @Zhengtq Hi, thanks for your great work!
> It seems that the code does not contain "Conv5"，which is used to mix up features. I attach the picture, "Conv5" has 1024 output channels.
> ![image](https://user-images.githubusercontent.com/20535427/88357232-260a7300-cd9d-11ea-990f-4f117186fb48.png)
> 
> As the paper says:
> The overall network structure is similar to ShufﬂeNet v1 [15] and summarized in Table 5. There is only one diﬀerence: an additional 1×1 convolution layer is added right before global averaged pooling to mix up features, which is absent in ShuﬄeNet v1.

Very thanks for your carefully pointing out. It's indeed my mistake. I have modified it now. Hope for more communication with you.
